-- Equipment-rental schema. Applied once by Liquibase (changeset 001-schema).

-- Users: customer, provider, and admin accounts.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    full_name     VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_role CHECK (role IN ('CUSTOMER', 'PROVIDER', 'ADMIN'))
);

-- Providers: equipment managers. One provider profile per user account.
CREATE TABLE providers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL UNIQUE REFERENCES users (id),
    business_name VARCHAR(255) NOT NULL,
    description   TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Services: rentable equipment items. asset_tag is the unique asset id.
CREATE TABLE services (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES providers (id),
    name        VARCHAR(255) NOT NULL,
    category    VARCHAR(100),
    description TEXT,
    asset_tag   VARCHAR(100) NOT NULL UNIQUE,
    daily_rate  NUMERIC(10, 2) NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_services_daily_rate CHECK (daily_rate >= 0),
    CONSTRAINT chk_services_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
);

CREATE INDEX idx_services_provider ON services (provider_id);

-- Availability slots: bookable time periods for a specific equipment item.
-- The owning provider is reached through the service, not stored here.
CREATE TABLE availability_slots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id  BIGINT NOT NULL REFERENCES services (id),
    starts_at   TIMESTAMPTZ NOT NULL,
    ends_at     TIMESTAMPTZ NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_slot_status CHECK (status IN ('OPEN', 'BLOCKED')),
    CONSTRAINT chk_slot_time_order CHECK (ends_at > starts_at),
    CONSTRAINT uq_slot_service_time UNIQUE (service_id, starts_at, ends_at)
);

CREATE INDEX idx_slots_starts_at ON availability_slots (starts_at);

-- Appointments: a customer's reservation of an availability slot.
-- The rented equipment is reached through the slot, not stored here.
CREATE TABLE appointments (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    availability_slot_id BIGINT NOT NULL REFERENCES availability_slots (id),
    customer_id          BIGINT NOT NULL REFERENCES users (id),
    status               VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_appt_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'))
);

CREATE INDEX idx_appointments_customer ON appointments (customer_id);
CREATE INDEX idx_appointments_slot ON appointments (availability_slot_id);

-- Double-booking guard: at most one active (PENDING/CONFIRMED) appointment per slot.
CREATE UNIQUE INDEX uq_active_appointment_slot
    ON appointments (availability_slot_id)
    WHERE status IN ('PENDING', 'CONFIRMED');
